[package]
name = "tic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
llama_cpp = { version = "0.3.2", features = ["metal"] }
